language: php

php:
  - 7.4

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script: ./vendor/bin/phpunit  --coverage-clover build/logs/clover.xml tests

after_success:
  - travis_retry php vendor/bin/php-coveralls